import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.why-argentina': 'Por qué Argentina',
    'nav.services': 'Servicios',
    'nav.process': 'Proceso',
    'nav.case-studies': 'Casos Reales',
    'nav.resources': 'Recursos',
    'nav.pricing': 'Tarifas',
    'nav.blog': 'Blog',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'header.schedule-consultation': 'Agenda consulta',
    
    // Hero Section
    'hero.title.part1': 'Tu acceso al',
    'hero.title.part2': 'futuro inmobiliario',
    'hero.title.part3': 'de Buenos Aires',
    'hero.subtitle': 'Navegamos la complejidad del mercado argentino para transformar las dudas en oportunidades de renta excepcionales. Acompañamiento integral desde la estrategia hasta la ejecución.',
    'hero.schedule-consultation': 'Agenda tu consulta',
    'hero.watch-presentation': 'Ver presentación',
    'hero.free-consultation': 'Consulta inicial sin costo',
    'hero.total-transparency': 'Transparencia total',
    'hero.secure-remote': 'Operación remota segura',
    'hero.play-teaser': 'Reproducir teaser',
    'hero.teaser-description': 'Descubre cómo convertimos la volatilidad argentina en rentabilidad predecible',
    'hero.average-roi': 'ROI promedio',
    'hero.upside-potential': 'Potencial alcista',
    
    // Data Section
    'data.title': 'Los números no mienten',
    'data.subtitle': 'Datos comparativos que demuestran el momento excepcional para invertir en Buenos Aires',
    'data.international-comparison': 'Comparativa internacional (USD/m²)',
    
    // Philosophy Section
    'philosophy.badge': 'Filosofía Antifragile',
    'philosophy.title.part1': 'Prosperamos en la',
    'philosophy.title.part2': 'incertidumbre',
    'philosophy.subtitle': 'Mientras otros temen la volatilidad, nosotros la aprovechamos. Buenos Aires ofrece oportunidades únicas para inversionistas que entienden cómo navegar la complejidad.',
    'philosophy.exceptional-returns.title': 'Retornos Excepcionales',
    'philosophy.exceptional-returns.description': 'ROI del 8-15% anual en USD. Precios 60% por debajo de máximos históricos crean oportunidades irrepetibles.',
    'philosophy.exceptional-returns.stat': 'potencial de apreciación',
    'philosophy.legal-security.title': 'Seguridad Jurídica',
    'philosophy.legal-security.description': 'Due diligence exhaustivo, escribano certificado y poder notarial para operaciones 100% remotas y seguras.',
    'philosophy.legal-security.stat': 'operaciones exitosas',
    'philosophy.boutique-service.title': 'Servicio Boutique',
    'philosophy.boutique-service.description': 'Desde estrategia hasta gestión de renta. Un equipo especializado dedicado exclusivamente a tu éxito.',
    'philosophy.boutique-service.stat': 'acompañamiento integral',
    
    // Process Section
    'process.badge': 'Metodología Probada',
    'process.title.part1': 'De la estrategia a la',
    'process.title.part2': 'rentabilidad',
    'process.subtitle': 'Un proceso refinado que transforma conceptos complejos en resultados tangibles',
    'process.step1.title': 'Consulta Estratégica',
    'process.step1.description': 'Sesión inicial de 30 minutos para comprender tus objetivos, apetito de riesgo y definir la estrategia de inversión óptima.',
    'process.step2.title': 'Curación & Análisis',
    'process.step2.description': 'Identificación de oportunidades premium. Due diligence completo de propiedades, documentación y potencial de rentabilidad.',
    'process.step3.title': 'Ejecución & Gestión',
    'process.step3.description': 'Cierre notarial remoto, optimización del activo y gestión integral de renta desde el primer día.',
    'process.explore-methodology': 'Explorar metodología completa',

    // Testimonials
    'testimonials.badge': 'Casos de Éxito',
    'testimonials.title': 'Inversionistas que confiaron',
    'testimonials.subtitle': 'Profesionales de todo el mundo han elegido nuestra expertise para sus inversiones en Buenos Aires',
    'testimonials.see-more': 'Ver más casos de éxito',
    'testimonials.quote1': '"ROI del 14% en el primer año. El proceso fue impecablemente profesional y completamente transparente desde el inicio."',
    'testimonials.quote2': '"Operación 100% remota desde Madrid. Seguridad jurídica absoluta y acompañamiento en cada detalle del proceso."',
    'testimonials.quote3': '"Mejor decisión de inversión en años. Combina rentabilidad excepcional con un servicio verdaderamente boutique."',

    // Blog Page
    'blog.title': 'Insights & Análisis',
    'blog.subtitle': 'Perspectivas profundas sobre inversiones inmobiliarias en Argentina',
    'blog.featured-articles': 'Artículos destacados',
    'blog.all-articles': 'Todos los artículos',
    'blog.newsletter.title': 'Mantente informado',
    'blog.newsletter.subtitle': 'Recibe análisis exclusivos y oportunidades de inversión directamente en tu email',
    'blog.newsletter.placeholder': 'Tu email',
    'blog.newsletter.subscribe': 'Suscribirse',
    'blog.newsletter.success': '¡Suscripción exitosa!',
    'blog.newsletter.success.description': 'Te has suscrito correctamente a nuestro newsletter',
    'blog.newsletter.error': 'Error',
    'blog.newsletter.error.invalid': 'Por favor ingresa un email válido',
    'blog.newsletter.error.general': 'Hubo un error al suscribirse. Inténtalo nuevamente.',
    'blog.read-more': 'Leer más',
    'blog.back-to-blog': 'Volver al blog',
    'blog.reading-time': 'lectura',

    // Why Argentina Page
    'why-argentina.title': '¿Por qué Argentina ahora?',
    'why-argentina.subtitle': 'Una tesis de inversión respaldada por datos duros, ciclos económicos y una oportunidad histórica de comprar activos de calidad mundial a precios de mercados emergentes.',
    'why-argentina.watch-analysis': 'Ver análisis completo',
    'why-argentina.download-pdf': 'Descargar PDF gratuito',
    'why-argentina.macroeconomic-data': 'Datos macroeconómicos',
    'why-argentina.historical-cycles': 'Ciclos históricos',
    'why-argentina.expert-analysis': 'Análisis experto',
    'why-argentina.historic-opportunity': 'Oportunidad histórica',
    'why-argentina.play-analysis': 'Reproducir análisis',
    'why-argentina.potential-multiplier': 'Multiplicador potencial',
    'why-argentina.video-version': 'Versión video',
    'why-argentina.complete-analysis': 'Análisis completo (5-7 min)',
    'why-argentina.executive-pdf': 'PDF ejecutivo',
    'why-argentina.free-download': 'Descarga gratuita',
    'why-argentina.numbers-dont-lie': 'Los números no mienten',
    'why-argentina.numbers-subtitle': 'Datos comparativos que demuestran el momento excepcional para invertir en Buenos Aires',
    'why-argentina.international-comparison': 'Comparativa internacional (USD/m²)',
    'why-argentina.catalysts-title': 'Catalizadores de crecimiento',
    'why-argentina.catalysts-subtitle': 'Factores macro que impulsan la revalorización inmobiliaria en el mediano plazo',
    'why-argentina.political-cycle': 'Ciclo Político',
    'why-argentina.political-cycle.description': 'Nuevo gobierno pro-mercado. Políticas de apertura económica y normalización del tipo de cambio.',
    'why-argentina.vaca-muerta': 'Vaca Muerta',
    'why-argentina.vaca-muerta.description': 'Segundo yacimiento de gas no convencional del mundo. Potencial de ingresos por $200B+ en 20 años.',
    'why-argentina.exchange-rate': 'Tipo de Cambio',
    'why-argentina.exchange-rate.description': 'Unificación cambiaria inminente. Corrección hacia equilibrio de largo plazo favorece activos locales.',
    'why-argentina.risks-title': '¿Riesgos y cómo los mitigamos?',
    'why-argentina.risks-subtitle': 'Transparencia total sobre los desafíos y nuestras estrategias de mitigación',
    'why-argentina.risk1.title': 'Riesgo: Inestabilidad política / económica',
    'why-argentina.risk1.mitigation': 'Inversión en activos físicos (ladrillo) denominados en USD. Diversificación por barrios y tipos de propiedad. Contratos de alquiler en moneda dura.',
    'why-argentina.risk2.title': 'Riesgo: Regulaciones de alquiler',
    'why-argentina.risk2.mitigation': 'Estructuras legales robustas. Monitoreo regulatorio constante. Flexibilidad entre alquiler tradicional y temporario (Airbnb) según cambios normativos.',
    'why-argentina.risk3.title': 'Riesgo: Liquidez y salida',
    'why-argentina.risk3.mitigation': 'Selección de propiedades en zonas prime con alta demanda. Red de compradores locales e internacionales. Estrategia de salida planificada desde el día 1.',
    'why-argentina.schedule-consultation': 'Agenda una consulta',
    
    // Footer
    'footer.company': 'Empresa',
    'footer.company-description': 'Transformamos la incertidumbre del mercado argentino en oportunidades de inversión excepcionales. Expertise boutique para inversionistas sofisticados.',
    'footer.services': 'Servicios',
    'footer.service.strategic-consulting': 'Consultoría Estratégica',
    'footer.service.property-curation': 'Curación de Inmuebles',
    'footer.service.financial-structuring': 'Estructuración Financiera',
    'footer.service.legal-due-diligence': 'Due Diligence Legal',
    'footer.service.asset-optimization': 'Optimización de Activos',
    'footer.service.integral-management': 'Gestión Integral',
    'footer.resources': 'Recursos',
    'footer.resource.investment-thesis': 'Tesis de Inversión',
    'footer.resource.research-analysis': 'Research & Análisis',
    'footer.resource.market-intelligence': 'Market Intelligence',
    'footer.resource.roi-calculator': 'Calculadora ROI',
    'footer.resource.success-cases': 'Casos de Éxito',
    'footer.resource.team': 'Equipo',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter-subtitle': 'Mantente al día con insights exclusivos',
    'footer.email-placeholder': 'Tu email',
    'footer.subscribe': 'Suscribirse',
    'footer.rights': 'Todos los derechos reservados',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',

    // Services Page
    'services.title': 'Servicios 360°',
    'services.subtitle': 'Todo lo que necesitas para invertir exitosamente en Buenos Aires. Desde la primera consulta hasta la gestión de alquiler, nos encargamos de cada detalle.',
    'services.main-title': 'Servicios principales',
    'services.main-subtitle': 'Cada servicio está diseñado para eliminar fricciones y maximizar tu retorno de inversión',
    'services.advisory.title': 'Asesoría 1-a-1',
    'services.advisory.price': '300 USD/hora',
    'services.advisory.description': 'Consultoría personalizada con expertos locales. Análisis de tu perfil de inversión y recomendaciones específicas.',
    'services.advisory.feature1': 'Análisis de perfil de riesgo',
    'services.advisory.feature2': 'Recomendaciones de barrios',
    'services.advisory.feature3': 'Estrategia de financiamiento',
    'services.advisory.feature4': 'Proyección de ROI personalizada',
    'services.search.title': 'Zona & Búsqueda',
    'services.search.price': 'Incluido en packs',
    'services.search.description': 'Investigación profunda de barrios y búsqueda activa de propiedades que cumplan tus criterios específicos.',
    'services.search.feature1': 'Análisis demográfico detallado',
    'services.search.feature2': 'Proyección de crecimiento urbano',
    'services.search.feature3': 'Búsqueda activa de propiedades',
    'services.search.feature4': 'Due diligence completo',
    'services.exchange.title': 'Cambio de Divisas',
    'services.exchange.price': 'Mejor rate del mercado',
    'services.exchange.description': 'Conversión USDT/crypto a USD billete o ARS al mejor tipo de cambio. Proceso seguro y trazable.',
    'services.exchange.feature1': 'USDT → USD billete',
    'services.exchange.feature2': 'Crypto → ARS',
    'services.exchange.feature3': 'Rate competitivo garantizado',
    'services.exchange.feature4': 'Transferencias seguras y rápidas',
    'services.legal.title': 'Documentación Legal',
    'services.legal.price': 'Pack integral',
    'services.legal.description': 'Gestión completa de CUIT/CDI, documentación fiscal y estructuras legales para inversores extranjeros.',
    'services.legal.feature1': 'Tramitación CUIT/CDI',
    'services.legal.feature2': 'Apertura cuenta bancaria',
    'services.legal.feature3': 'Estructuras fiscales óptimas',
    'services.legal.feature4': 'Documentación apostillada',
    'services.notary.title': 'Escribano & Poder',
    'services.notary.price': 'Cierre remoto seguro',
    'services.notary.description': 'Escribano certificado y poder notarial para compra remota. Cierre 100% a distancia con garantías legales.',
    'services.notary.feature1': 'Escribano de confianza',
    'services.notary.feature2': 'Poder notarial internacional',
    'services.notary.feature3': 'Verificación de títulos',
    'services.notary.feature4': 'Cierre remoto certificado',
    'services.renovation.title': 'Remodelación Turnkey',
    'services.renovation.price': 'Proyecto integral',
    'services.renovation.description': 'Diseño, remodelación e interiorismo completo. De la compra al alquiler sin que tengas que viajar.',
    'services.renovation.feature1': 'Diseño arquitectónico',
    'services.renovation.feature2': 'Gestión de obra completa',
    'services.renovation.feature3': 'Interiorismo profesional',
    'services.renovation.feature4': 'Entrega llave en mano',
    'services.rental-title': 'Gestión de Alquiler',
    'services.rental-subtitle': 'Dos modalidades de alquiler para maximizar tu retorno según tu perfil de riesgo y objetivos',
    'services.traditional.title': 'Alquiler Tradicional',
    'services.traditional.description': 'Gestión de alquiler residencial de largo plazo. Máxima estabilidad y previsibilidad de ingresos.',
    'services.traditional.feature1': 'Contratos 2-3 años',
    'services.traditional.feature2': 'Inquilinos verificados',
    'services.traditional.feature3': 'Garantías sólidas',
    'services.traditional.feature4': 'Administración completa',
    'services.airbnb.title': 'Airbnb / Estudiantes',
    'services.airbnb.description': 'Alquiler temporario y a estudiantes internacionales. Mayor rotación pero yields superiores.',
    'services.airbnb.feature1': 'Gestión Airbnb completa',
    'services.airbnb.feature2': 'Alquiler a estudiantes',
    'services.airbnb.feature3': 'Yields 15-25% superiores',
    'services.airbnb.feature4': 'Mantenimiento incluido',
    'services.rental-question': '¿No estás seguro cuál modalidad te conviene más?',
    'services.rental-button': 'Consulta personalizada gratuita',
    'services.rental-button-mobile': 'Consulta personalizada',
    'services.guarantee-title': 'Garantía de satisfacción 100%',
    'services.guarantee-subtitle': 'Si no estás completamente satisfecho con nuestro servicio en los primeros 30 días, te devolvemos el 100% de tu inversión. Sin preguntas.',
    'services.guarantee-stat1': '100%',
    'services.guarantee-label1': 'Operaciones exitosas',
    'services.guarantee-stat2': '24/7',
    'services.guarantee-label2': 'Soporte disponible',
    'services.guarantee-stat3': '30 días',
    'services.guarantee-label3': 'Garantía de devolución',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.contact': 'Contacto',
    'common.email': 'Email',
    'common.phone': 'Teléfono',
    'common.name': 'Nombre',
    'common.send': 'Enviar',
    'common.read-more': 'Leer más',
    'common.learn-more': 'Saber más',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.why-argentina': 'Why Argentina',
    'nav.services': 'Services',
    'nav.process': 'Process',
    'nav.case-studies': 'Case Studies',
    'nav.resources': 'Resources',
    'nav.pricing': 'Pricing',
    'nav.blog': 'Blog',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'header.schedule-consultation': 'Schedule consultation',
    
    // Hero Section
    'hero.title.part1': 'Your gateway to',
    'hero.title.part2': 'Buenos Aires',
    'hero.title.part3': 'real estate future',
    'hero.subtitle': 'We navigate the complexity of the Argentine market to transform doubts into exceptional rental opportunities. Comprehensive support from strategy to execution.',
    'hero.schedule-consultation': 'Schedule your consultation',
    'hero.watch-presentation': 'Watch presentation',
    'hero.free-consultation': 'Free initial consultation',
    'hero.total-transparency': 'Total transparency',
    'hero.secure-remote': 'Secure remote operation',
    'hero.play-teaser': 'Play teaser',
    'hero.teaser-description': 'Discover how we turn Argentine volatility into predictable profitability',
    'hero.average-roi': 'Average ROI',
    'hero.upside-potential': 'Upside potential',
    
    // Data Section
    'data.title': 'Numbers don\'t lie',
    'data.subtitle': 'Comparative data demonstrating the exceptional moment to invest in Buenos Aires',
    'data.international-comparison': 'International comparison (USD/m²)',
    
    // Philosophy Section
    'philosophy.badge': 'Antifragile Philosophy',
    'philosophy.title.part1': 'We thrive in',
    'philosophy.title.part2': 'uncertainty',
    'philosophy.subtitle': 'While others fear volatility, we leverage it. Buenos Aires offers unique opportunities for investors who understand how to navigate complexity.',
    'philosophy.exceptional-returns.title': 'Exceptional Returns',
    'philosophy.exceptional-returns.description': '8-15% annual ROI in USD. Prices 60% below historical peaks create unrepeatable opportunities.',
    'philosophy.exceptional-returns.stat': 'appreciation potential',
    'philosophy.legal-security.title': 'Legal Security',
    'philosophy.legal-security.description': 'Exhaustive due diligence, certified notary and power of attorney for 100% remote and secure operations.',
    'philosophy.legal-security.stat': 'successful operations',
    'philosophy.boutique-service.title': 'Boutique Service',
    'philosophy.boutique-service.description': 'From strategy to rental management. A specialized team dedicated exclusively to your success.',
    'philosophy.boutique-service.stat': 'comprehensive support',
    
    // Process Section
    'process.badge': 'Proven Methodology',
    'process.title.part1': 'From strategy to',
    'process.title.part2': 'profitability',
    'process.subtitle': 'A refined process that transforms complex concepts into tangible results',
    'process.step1.title': 'Strategic Consultation',
    'process.step1.description': '30-minute initial session to understand your objectives, risk appetite and define the optimal investment strategy.',
    'process.step2.title': 'Curation & Analysis',
    'process.step2.description': 'Identification of premium opportunities. Complete due diligence of properties, documentation and profitability potential.',
    'process.step3.title': 'Execution & Management',
    'process.step3.description': 'Remote notarial closing, asset optimization and comprehensive rental management from day one.',
    'process.explore-methodology': 'Explore complete methodology',

    // Testimonials
    'testimonials.badge': 'Success Stories',
    'testimonials.title': 'Investors who trusted',
    'testimonials.subtitle': 'Professionals from around the world have chosen our expertise for their investments in Buenos Aires',
    'testimonials.see-more': 'See more success stories',
    'testimonials.quote1': '"14% ROI in the first year. The process was impeccably professional and completely transparent from the start."',
    'testimonials.quote2': '"100% remote operation from Madrid. Absolute legal security and support in every detail of the process."',
    'testimonials.quote3': '"Best investment decision in years. Combines exceptional profitability with truly boutique service."',

    // Blog Page
    'blog.title': 'Insights & Analysis',
    'blog.subtitle': 'Deep perspectives on real estate investments in Argentina',
    'blog.featured-articles': 'Featured articles',
    'blog.all-articles': 'All articles',
    'blog.newsletter.title': 'Stay informed',
    'blog.newsletter.subtitle': 'Receive exclusive analysis and investment opportunities directly in your email',
    'blog.newsletter.placeholder': 'Your email',
    'blog.newsletter.subscribe': 'Subscribe',
    'blog.newsletter.success': 'Subscription successful!',
    'blog.newsletter.success.description': 'You have successfully subscribed to our newsletter',
    'blog.newsletter.error': 'Error',
    'blog.newsletter.error.invalid': 'Please enter a valid email',
    'blog.newsletter.error.general': 'There was an error subscribing. Please try again.',
    'blog.read-more': 'Read more',
    'blog.back-to-blog': 'Back to blog',
    'blog.reading-time': 'read',

    // Why Argentina Page
    'why-argentina.title': 'Why Argentina now?',
    'why-argentina.subtitle': 'An investment thesis backed by hard data, economic cycles and a historic opportunity to buy world-class assets at emerging market prices.',
    'why-argentina.watch-analysis': 'Watch complete analysis',
    'why-argentina.download-pdf': 'Download free PDF',
    'why-argentina.macroeconomic-data': 'Macroeconomic data',
    'why-argentina.historical-cycles': 'Historical cycles',
    'why-argentina.expert-analysis': 'Expert analysis',
    'why-argentina.historic-opportunity': 'Historic opportunity',
    'why-argentina.play-analysis': 'Play analysis',
    'why-argentina.potential-multiplier': 'Potential multiplier',
    'why-argentina.video-version': 'Video version',
    'why-argentina.complete-analysis': 'Complete analysis (5-7 min)',
    'why-argentina.executive-pdf': 'Executive PDF',
    'why-argentina.free-download': 'Free download',
    'why-argentina.numbers-dont-lie': 'Numbers don\'t lie',
    'why-argentina.numbers-subtitle': 'Comparative data demonstrating the exceptional moment to invest in Buenos Aires',
    'why-argentina.international-comparison': 'International comparison (USD/m²)',
    'why-argentina.catalysts-title': 'Growth Catalysts',
    'why-argentina.catalysts-subtitle': 'Macro factors driving real estate appreciation in the medium term',
    'why-argentina.political-cycle': 'Political Cycle',
    'why-argentina.political-cycle.description': 'New pro-market government. Economic opening policies and exchange rate normalization.',
    'why-argentina.vaca-muerta': 'Vaca Muerta',
    'why-argentina.vaca-muerta.description': 'Second largest unconventional gas field in the world. Revenue potential of $200B+ over 20 years.',
    'why-argentina.exchange-rate': 'Exchange Rate',
    'why-argentina.exchange-rate.description': 'Imminent currency unification. Long-term equilibrium correction favors local assets.',
    'why-argentina.risks-title': 'Risks and how we mitigate them?',
    'why-argentina.risks-subtitle': 'Total transparency about challenges and our mitigation strategies',
    'why-argentina.risk1.title': 'Risk: Political/economic instability',
    'why-argentina.risk1.mitigation': 'Mitigation: Investment in physical assets (brick) denominated in USD. Diversification by neighborhoods and property types. Rental contracts in hard currency.',
    'why-argentina.risk2.title': 'Risk: Rental regulations',
    'why-argentina.risk2.mitigation': 'Mitigation: Robust legal structures. Constant regulatory monitoring. Flexibility between traditional rental and temporary (Airbnb) according to regulatory changes.',
    'why-argentina.risk3.title': 'Risk: Liquidity and exit',
    'why-argentina.risk3.mitigation': 'Mitigation: Selection of properties in prime areas with high demand. Network of local and international buyers. Exit strategy planned from day 1.',
    'why-argentina.schedule-consultation': 'Schedule a consultation',
    
    // Footer
    'footer.company': 'Company',
    'footer.company-description': 'We transform the uncertainty of the Argentine market into exceptional investment opportunities. Boutique expertise for sophisticated investors.',
    'footer.services': 'Services',
    'footer.service.strategic-consulting': 'Strategic Consulting',
    'footer.service.property-curation': 'Property Curation',
    'footer.service.financial-structuring': 'Financial Structuring',
    'footer.service.legal-due-diligence': 'Legal Due Diligence',
    'footer.service.asset-optimization': 'Asset Optimization',
    'footer.service.integral-management': 'Integral Management',
    'footer.resources': 'Resources',
    'footer.resource.investment-thesis': 'Investment Thesis',
    'footer.resource.research-analysis': 'Research & Analysis',
    'footer.resource.market-intelligence': 'Market Intelligence',
    'footer.resource.roi-calculator': 'ROI Calculator',
    'footer.resource.success-cases': 'Success Cases',
    'footer.resource.team': 'Team',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter-subtitle': 'Stay updated with exclusive insights',
    'footer.email-placeholder': 'Your email',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Services Page
    'services.title': '360° Services',
    'services.subtitle': 'Everything you need to successfully invest in Buenos Aires. From initial consultation to rental management, we handle every detail.',
    'services.main-title': 'Main Services',
    'services.main-subtitle': 'Each service is designed to eliminate friction and maximize your return on investment',
    'services.advisory.title': '1-on-1 Advisory',
    'services.advisory.price': '300 USD/hour',
    'services.advisory.description': 'Personalized consulting with local experts. Investment profile analysis and specific recommendations.',
    'services.advisory.feature1': 'Risk profile analysis',
    'services.advisory.feature2': 'Neighborhood recommendations',
    'services.advisory.feature3': 'Financing strategy',
    'services.advisory.feature4': 'Personalized ROI projection',
    'services.search.title': 'Area & Search',
    'services.search.price': 'Included in packages',
    'services.search.description': 'In-depth neighborhood research and active property search that meets your specific criteria.',
    'services.search.feature1': 'Detailed demographic analysis',
    'services.search.feature2': 'Urban growth projection',
    'services.search.feature3': 'Active property search',
    'services.search.feature4': 'Complete due diligence',
    'services.exchange.title': 'Currency Exchange',
    'services.exchange.price': 'Best market rate',
    'services.exchange.description': 'USDT/crypto to USD cash or ARS conversion at the best exchange rate. Secure and traceable process.',
    'services.exchange.feature1': 'USDT → USD cash',
    'services.exchange.feature2': 'Crypto → ARS',
    'services.exchange.feature3': 'Guaranteed competitive rate',
    'services.exchange.feature4': 'Secure and fast transfers',
    'services.legal.title': 'Legal Documentation',
    'services.legal.price': 'Comprehensive package',
    'services.legal.description': 'Complete CUIT/CDI management, tax documentation and legal structures for foreign investors.',
    'services.legal.feature1': 'CUIT/CDI processing',
    'services.legal.feature2': 'Bank account opening',
    'services.legal.feature3': 'Optimal tax structures',
    'services.legal.feature4': 'Apostilled documentation',
    'services.notary.title': 'Notary & Power of Attorney',
    'services.notary.price': 'Secure remote closing',
    'services.notary.description': 'Certified notary and power of attorney for remote purchase. 100% remote closing with legal guarantees.',
    'services.notary.feature1': 'Trusted notary',
    'services.notary.feature2': 'International power of attorney',
    'services.notary.feature3': 'Title verification',
    'services.notary.feature4': 'Certified remote closing',
    'services.renovation.title': 'Turnkey Renovation',
    'services.renovation.price': 'Comprehensive project',
    'services.renovation.description': 'Complete design, renovation and interior design. From purchase to rental without you having to travel.',
    'services.renovation.feature1': 'Architectural design',
    'services.renovation.feature2': 'Complete project management',
    'services.renovation.feature3': 'Professional interior design',
    'services.renovation.feature4': 'Turnkey delivery',
    'services.rental-title': 'Rental Management',
    'services.rental-subtitle': 'Two rental modalities to maximize your return according to your risk profile and objectives',
    'services.traditional.title': 'Traditional Rental',
    'services.traditional.description': 'Long-term residential rental management. Maximum stability and income predictability.',
    'services.traditional.feature1': '2-3 year contracts',
    'services.traditional.feature2': 'Verified tenants',
    'services.traditional.feature3': 'Solid guarantees',
    'services.traditional.feature4': 'Complete administration',
    'services.airbnb.title': 'Airbnb / Students',
    'services.airbnb.description': 'Temporary rental and international students. Higher rotation but superior yields.',
    'services.airbnb.feature1': 'Complete Airbnb management',
    'services.airbnb.feature2': 'Student rentals',
    'services.airbnb.feature3': '15-25% higher yields',
    'services.airbnb.feature4': 'Maintenance included',
    'services.rental-question': 'Not sure which modality suits you best?',
    'services.rental-button': 'Free personalized consultation',
    'services.rental-button-mobile': 'Personalized consultation',
    'services.guarantee-title': '100% Satisfaction Guarantee',
    'services.guarantee-subtitle': 'If you\'re not completely satisfied with our service in the first 30 days, we\'ll refund 100% of your investment. No questions asked.',
    'services.guarantee-stat1': '100%',
    'services.guarantee-label1': 'Successful operations',
    'services.guarantee-stat2': '24/7',
    'services.guarantee-label2': 'Available support',
    'services.guarantee-stat3': '30 days',
    'services.guarantee-label3': 'Money-back guarantee',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.contact': 'Contact',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.name': 'Name',
    'common.send': 'Send',
    'common.read-more': 'Read more',
    'common.learn-more': 'Learn more',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};