import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.why-argentina': 'Por qué Argentina',
    'nav.services': 'Servicios',
    'nav.process': 'Proceso',
    'nav.case-studies': 'Casos Reales',
    'nav.resources': 'Recursos',
    'nav.pricing': 'Tarifas',
    'nav.blog': 'Blog',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'header.schedule-consultation': 'Agenda consulta',
    
    // Hero Section
    'hero.title.part1': 'Tu acceso al',
    'hero.title.part2': 'futuro inmobiliario',
    'hero.title.part3': 'de Buenos Aires',
    'hero.subtitle': 'Navegamos la complejidad del mercado argentino para transformar las dudas en oportunidades de renta excepcionales. Acompañamiento integral desde la estrategia hasta la ejecución.',
    'hero.schedule-consultation': 'Agenda tu consulta',
    'hero.watch-presentation': 'Ver presentación',
    'hero.free-consultation': 'Consulta inicial sin costo',
    'hero.total-transparency': 'Transparencia total',
    'hero.secure-remote': 'Operación remota segura',
    'hero.play-teaser': 'Reproducir teaser',
    'hero.teaser-description': 'Descubre cómo convertimos la volatilidad argentina en rentabilidad predecible',
    'hero.average-roi': 'ROI promedio',
    'hero.upside-potential': 'Potencial alcista',
    
    // Data Section
    'data.title': 'Los números no mienten',
    'data.subtitle': 'Datos comparativos que demuestran el momento excepcional para invertir en Buenos Aires',
    'data.international-comparison': 'Comparativa internacional (USD/m²)',
    
    // Philosophy Section
    'philosophy.badge': 'Filosofía Antifragile',
    'philosophy.title.part1': 'Prosperamos en la',
    'philosophy.title.part2': 'incertidumbre',
    'philosophy.subtitle': 'Mientras otros temen la volatilidad, nosotros la aprovechamos. Buenos Aires ofrece oportunidades únicas para inversionistas que entienden cómo navegar la complejidad.',
    'philosophy.exceptional-returns.title': 'Retornos Excepcionales',
    'philosophy.exceptional-returns.description': 'ROI del 8-15% anual en USD. Precios 60% por debajo de máximos históricos crean oportunidades irrepetibles.',
    'philosophy.exceptional-returns.stat': 'potencial de apreciación',
    'philosophy.legal-security.title': 'Seguridad Jurídica',
    'philosophy.legal-security.description': 'Due diligence exhaustivo, escribano certificado y poder notarial para operaciones 100% remotas y seguras.',
    'philosophy.legal-security.stat': 'operaciones exitosas',
    'philosophy.boutique-service.title': 'Servicio Boutique',
    'philosophy.boutique-service.description': 'Desde estrategia hasta gestión de renta. Un equipo especializado dedicado exclusivamente a tu éxito.',
    'philosophy.boutique-service.stat': 'acompañamiento integral',
    

    // Testimonials
    'testimonials.badge': 'Casos de Éxito',
    'testimonials.title': 'Inversionistas que confiaron',
    'testimonials.subtitle': 'Profesionales de todo el mundo han elegido nuestra expertise para sus inversiones en Buenos Aires',
    'testimonials.see-more': 'Ver más casos de éxito',
    'testimonials.quote1': '"ROI del 14% en el primer año. El proceso fue impecablemente profesional y completamente transparente desde el inicio."',
    'testimonials.quote2': '"Operación 100% remota desde Madrid. Seguridad jurídica absoluta y acompañamiento en cada detalle del proceso."',
    'testimonials.quote3': '"Mejor decisión de inversión en años. Combina rentabilidad excepcional con un servicio verdaderamente boutique."',

    // Blog Page
    'blog.title': 'Insights & Análisis',
    'blog.subtitle': 'Perspectivas profundas sobre inversiones inmobiliarias en Argentina',
    'blog.featured-articles': 'Artículos destacados',
    'blog.all-articles': 'Todos los artículos',
    'blog.newsletter.title': 'Mantente informado',
    'blog.newsletter.subtitle': 'Recibe análisis exclusivos y oportunidades de inversión directamente en tu email',
    'blog.newsletter.placeholder': 'Tu email',
    'blog.newsletter.subscribe': 'Suscribirse',
    'blog.newsletter.success': '¡Suscripción exitosa!',
    'blog.newsletter.success.description': 'Te has suscrito correctamente a nuestro newsletter',
    'blog.newsletter.error': 'Error',
    'blog.newsletter.error.invalid': 'Por favor ingresa un email válido',
    'blog.newsletter.error.general': 'Hubo un error al suscribirse. Inténtalo nuevamente.',
    'blog.read-more': 'Leer más',
    'blog.back-to-blog': 'Volver al blog',
    'blog.reading-time': 'lectura',

    // Why Argentina Page
    'why-argentina.title': '¿Por qué Argentina ahora?',
    'why-argentina.subtitle': 'Una tesis de inversión respaldada por datos duros, ciclos económicos y una oportunidad histórica de comprar activos de calidad mundial a precios de mercados emergentes.',
    'why-argentina.watch-analysis': 'Ver análisis completo',
    'why-argentina.download-pdf': 'Descargar PDF gratuito',
    'why-argentina.macroeconomic-data': 'Datos macroeconómicos',
    'why-argentina.historical-cycles': 'Ciclos históricos',
    'why-argentina.expert-analysis': 'Análisis experto',
    'why-argentina.historic-opportunity': 'Oportunidad histórica',
    'why-argentina.play-analysis': 'Reproducir análisis',
    'why-argentina.potential-multiplier': 'Multiplicador potencial',
    'why-argentina.video-version': 'Versión video',
    'why-argentina.complete-analysis': 'Análisis completo (5-7 min)',
    'why-argentina.executive-pdf': 'PDF ejecutivo',
    'why-argentina.free-download': 'Descarga gratuita',
    'why-argentina.numbers-dont-lie': 'Los números no mienten',
    'why-argentina.numbers-subtitle': 'Datos comparativos que demuestran el momento excepcional para invertir en Buenos Aires',
    'why-argentina.international-comparison': 'Comparativa internacional (USD/m²)',
    'why-argentina.catalysts-title': 'Catalizadores de crecimiento',
    'why-argentina.catalysts-subtitle': 'Factores macro que impulsan la revalorización inmobiliaria en el mediano plazo',
    'why-argentina.political-cycle': 'Ciclo Político',
    'why-argentina.political-cycle.description': 'Nuevo gobierno pro-mercado. Políticas de apertura económica y normalización del tipo de cambio.',
    'why-argentina.vaca-muerta': 'Vaca Muerta',
    'why-argentina.vaca-muerta.description': 'Segundo yacimiento de gas no convencional del mundo. Potencial de ingresos por $200B+ en 20 años.',
    'why-argentina.exchange-rate': 'Tipo de Cambio',
    'why-argentina.exchange-rate.description': 'Unificación cambiaria inminente. Corrección hacia equilibrio de largo plazo favorece activos locales.',
    'why-argentina.risks-title': '¿Riesgos y cómo los mitigamos?',
    'why-argentina.risks-subtitle': 'Transparencia total sobre los desafíos y nuestras estrategias de mitigación',
    'why-argentina.risk1.title': 'Riesgo: Inestabilidad política / económica',
    'why-argentina.risk1.mitigation': 'Inversión en activos físicos (ladrillo) denominados en USD. Diversificación por barrios y tipos de propiedad. Contratos de alquiler en moneda dura.',
    'why-argentina.risk2.title': 'Riesgo: Regulaciones de alquiler',
    'why-argentina.risk2.mitigation': 'Estructuras legales robustas. Monitoreo regulatorio constante. Flexibilidad entre alquiler tradicional y temporario (Airbnb) según cambios normativos.',
    'why-argentina.risk3.title': 'Riesgo: Liquidez y salida',
    'why-argentina.risk3.mitigation': 'Selección de propiedades en zonas prime con alta demanda. Red de compradores locales e internacionales. Estrategia de salida planificada desde el día 1.',
    'why-argentina.schedule-consultation': 'Agenda una consulta',
    
    // Footer
    'footer.company': 'Empresa',
    'footer.company-description': 'Transformamos la incertidumbre del mercado argentino en oportunidades de inversión excepcionales. Expertise boutique para inversionistas sofisticados.',
    'footer.services': 'Servicios',
    'footer.service.strategic-consulting': 'Consultoría Estratégica',
    'footer.service.property-curation': 'Curación de Inmuebles',
    'footer.service.financial-structuring': 'Estructuración Financiera',
    'footer.service.legal-due-diligence': 'Due Diligence Legal',
    'footer.service.asset-optimization': 'Optimización de Activos',
    'footer.service.integral-management': 'Gestión Integral',
    'footer.resources': 'Recursos',
    'footer.resource.investment-thesis': 'Tesis de Inversión',
    'footer.resource.research-analysis': 'Research & Análisis',
    'footer.resource.market-intelligence': 'Market Intelligence',
    'footer.resource.roi-calculator': 'Calculadora ROI',
    'footer.resource.success-cases': 'Casos de Éxito',
    'footer.resource.team': 'Equipo',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter-subtitle': 'Mantente al día con insights exclusivos',
    'footer.email-placeholder': 'Tu email',
    'footer.subscribe': 'Suscribirse',
    'footer.rights': 'Todos los derechos reservados',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',

    // Services Page
    'services.title': 'Servicios 360°',
    'services.subtitle': 'Todo lo que necesitas para invertir exitosamente en Buenos Aires. Desde la primera consulta hasta la gestión de alquiler, nos encargamos de cada detalle.',
    'services.main-title': 'Servicios principales',
    'services.main-subtitle': 'Cada servicio está diseñado para eliminar fricciones y maximizar tu retorno de inversión',
    'services.advisory.title': 'Asesoría 1-a-1',
    'services.advisory.price': '300 USD/hora',
    'services.advisory.description': 'Consultoría personalizada con expertos locales. Análisis de tu perfil de inversión y recomendaciones específicas.',
    'services.advisory.feature1': 'Análisis de perfil de riesgo',
    'services.advisory.feature2': 'Recomendaciones de barrios',
    'services.advisory.feature3': 'Estrategia de financiamiento',
    'services.advisory.feature4': 'Proyección de ROI personalizada',
    'services.search.title': 'Zona & Búsqueda',
    'services.search.price': 'Incluido en packs',
    'services.search.description': 'Investigación profunda de barrios y búsqueda activa de propiedades que cumplan tus criterios específicos.',
    'services.search.feature1': 'Análisis demográfico detallado',
    'services.search.feature2': 'Proyección de crecimiento urbano',
    'services.search.feature3': 'Búsqueda activa de propiedades',
    'services.search.feature4': 'Due diligence completo',
    'services.exchange.title': 'Cambio de Divisas',
    'services.exchange.price': 'Mejor rate del mercado',
    'services.exchange.description': 'Conversión USDT/crypto a USD billete o ARS al mejor tipo de cambio. Proceso seguro y trazable.',
    'services.exchange.feature1': 'USDT → USD billete',
    'services.exchange.feature2': 'Crypto → ARS',
    'services.exchange.feature3': 'Rate competitivo garantizado',
    'services.exchange.feature4': 'Transferencias seguras y rápidas',
    'services.legal.title': 'Documentación Legal',
    'services.legal.price': 'Pack integral',
    'services.legal.description': 'Gestión completa de CUIT/CDI, documentación fiscal y estructuras legales para inversores extranjeros.',
    'services.legal.feature1': 'Tramitación CUIT/CDI',
    'services.legal.feature2': 'Apertura cuenta bancaria',
    'services.legal.feature3': 'Estructuras fiscales óptimas',
    'services.legal.feature4': 'Documentación apostillada',
    'services.notary.title': 'Escribano & Poder',
    'services.notary.price': 'Cierre remoto seguro',
    'services.notary.description': 'Escribano certificado y poder notarial para compra remota. Cierre 100% a distancia con garantías legales.',
    'services.notary.feature1': 'Escribano de confianza',
    'services.notary.feature2': 'Poder notarial internacional',
    'services.notary.feature3': 'Verificación de títulos',
    'services.notary.feature4': 'Cierre remoto certificado',
    'services.renovation.title': 'Remodelación Turnkey',
    'services.renovation.price': 'Proyecto integral',
    'services.renovation.description': 'Diseño, remodelación e interiorismo completo. De la compra al alquiler sin que tengas que viajar.',
    'services.renovation.feature1': 'Diseño arquitectónico',
    'services.renovation.feature2': 'Gestión de obra completa',
    'services.renovation.feature3': 'Interiorismo profesional',
    'services.renovation.feature4': 'Entrega llave en mano',
    'services.rental-title': 'Gestión de Alquiler',
    'services.rental-subtitle': 'Dos modalidades de alquiler para maximizar tu retorno según tu perfil de riesgo y objetivos',
    'services.traditional.title': 'Alquiler Tradicional',
    'services.traditional.description': 'Gestión de alquiler residencial de largo plazo. Máxima estabilidad y previsibilidad de ingresos.',
    'services.traditional.feature1': 'Contratos 2-3 años',
    'services.traditional.feature2': 'Inquilinos verificados',
    'services.traditional.feature3': 'Garantías sólidas',
    'services.traditional.feature4': 'Administración completa',
    'services.airbnb.title': 'Airbnb / Estudiantes',
    'services.airbnb.description': 'Alquiler temporario y a estudiantes internacionales. Mayor rotación pero yields superiores.',
    'services.airbnb.feature1': 'Gestión Airbnb completa',
    'services.airbnb.feature2': 'Alquiler a estudiantes',
    'services.airbnb.feature3': 'Yields 15-25% superiores',
    'services.airbnb.feature4': 'Mantenimiento incluido',
    'services.rental-question': '¿No estás seguro cuál modalidad te conviene más?',
    'services.rental-button': 'Consulta personalizada gratuita',
    'services.rental-button-mobile': 'Consulta personalizada',
    'services.guarantee-title': 'Garantía de satisfacción 100%',
    'services.guarantee-subtitle': 'Si no estás completamente satisfecho con nuestro servicio en los primeros 30 días, te devolvemos el 100% de tu inversión. Sin preguntas.',
    'services.guarantee-stat1': '100%',
    'services.guarantee-label1': 'Operaciones exitosas',
    'services.guarantee-stat2': '24/7',
    'services.guarantee-label2': 'Soporte disponible',
    'services.guarantee-stat3': '30 días',
    'services.guarantee-label3': 'Garantía de devolución',


    // Process Page
    'process.title': 'Nuestro Proceso',
    'process.subtitle': 'Un proceso probado que te lleva de la idea inicial a generar renta pasiva en menos de 3 meses. Transparente, predecible y con seguimiento paso a paso.',
    'process.average-time-title': 'Tiempo promedio',
    'process.average-time-value': '8-12 semanas',
    'process.average-time-desc': 'De consulta inicial a primer alquiler',
    'process.success-rate-title': 'Tasa de éxito',
    'process.success-rate-value': '100%',
    'process.success-rate-desc': 'Operaciones completadas exitosamente',
    'process.satisfaction-title': 'Satisfacción',
    'process.satisfaction-value': '100%',
    'process.satisfaction-desc': 'Clientes que recomiendan nuestro servicio',
    'process.steps-title': '5 pasos hacia tu inversión exitosa',
    'process.steps-subtitle': 'Cada paso está diseñado para minimizar riesgos y maximizar transparencia',
    'process.step1.title': 'Discovery Call Gratuita',
    'process.step1.duration': '15 minutos',
    'process.step1.description': 'Conocemos tus objetivos, presupuesto y perfil de riesgo. Definimos estrategia inicial y expectativas realistas.',
    'process.step1.detail1': 'Análisis de perfil de inversión',
    'process.step1.detail2': 'Definición de presupuesto disponible',
    'process.step1.detail3': 'Objetivos de rentabilidad y plazo',
    'process.step1.detail4': 'Recomendaciones iniciales de barrios',
    'process.step2.title': 'Mandato & Due Diligence',
    'process.step2.duration': '2-4 semanas',
    'process.step2.description': 'Búsqueda activa y análisis profundo de propiedades. Verificación legal, técnica y financiera completa.',
    'process.step2.detail1': 'Búsqueda activa en base a criterios',
    'process.step2.detail2': 'Verificación de títulos y documentación',
    'process.step2.detail3': 'Inspección técnica detallada',
    'process.step2.detail4': 'Análisis de rentabilidad proyectada',
    'process.step3.title': 'Oferta & Cierre Notarial',
    'process.step3.duration': '1-2 semanas',
    'process.step3.description': 'Negociación, oferta formal y cierre notarial remoto. Transferencia segura con poder certificado.',
    'process.step3.detail1': 'Negociación de precio y condiciones',
    'process.step3.detail2': 'Preparación de documentación legal',
    'process.step3.detail3': 'Cierre notarial con poder remoto',
    'process.step3.detail4': 'Transferencia de fondos segura',
    'process.step4.title': 'Proyecto de Obra',
    'process.step4.duration': '4-8 semanas',
    'process.step4.description': 'Diseño, remodelación e interiorismo turnkey. Supervisión completa hasta entrega llave en mano.',
    'process.step4.detail1': 'Diseño arquitectónico y decorativo',
    'process.step4.detail2': 'Gestión de permisos y contratistas',
    'process.step4.detail3': 'Supervisión de obra diaria',
    'process.step4.detail4': 'Entrega con mobiliario incluido',
    'process.step5.title': 'Administración Post-Compra',
    'process.step5.duration': 'Ongoing',
    'process.step5.description': 'Gestión completa del alquiler, mantenimiento y administración. Reportes mensuales de performance.',
    'process.step5.detail1': 'Búsqueda y verificación de inquilinos',
    'process.step5.detail2': 'Gestión de contratos y cobros',
    'process.step5.detail3': 'Mantenimiento preventivo y correctivo',
    'process.step5.detail4': 'Reportes mensuales de rentabilidad',
    'process.includes': 'Incluye:',
    'process.timeline-title': 'Timeline típico de proyecto',
    'process.timeline-subtitle': 'Cronograma semanal desde el primer contacto hasta generar renta',
    'process.timeline.week1': 'Semana 1',
    'process.timeline.milestone1': 'Discovery call + Mandato de búsqueda',
    'process.timeline.week2': 'Semana 2-3',
    'process.timeline.milestone2': 'Presentación de opciones preseleccionadas',
    'process.timeline.week3': 'Semana 4',
    'process.timeline.milestone3': 'Due diligence + Oferta formal',
    'process.timeline.week4': 'Semana 5',
    'process.timeline.milestone4': 'Cierre notarial + Transferencia',
    'process.timeline.week5': 'Semana 6-12',
    'process.timeline.milestone5': 'Proyecto de obra + Remodelación',
    'process.timeline.week6': 'Semana 13',
    'process.timeline.milestone6': 'Puesta a renta + Primer inquilino',
    'process.final-title': '¡Tu propiedad generando renta!',
    'process.final-description': 'Al final del proceso tendrás un activo de calidad generando ingresos pasivos en USD.',
    'process.cta-title': '¿Listo para comenzar?',
    'process.cta-subtitle': 'El primer paso es siempre una consulta gratuita de 15 minutos. Sin compromiso, solo para conocerte y ver si somos el fit correcto.',
    'process.cta-button': 'Agenda tu consulta gratuita',
    'process.cta-button-mobile': 'Agenda tu consulta',
    'process.cta-pricing': 'Ver tarifas y packs',
    'process.cta-benefit1': 'Sin compromiso inicial',
    'process.cta-benefit2': 'Consulta 100% gratuita',
    'process.cta-benefit3': 'Respuesta en 24h',

    // Case Studies Page
    'case-studies.badge': 'Portfolio de Éxito',
    'case-studies.title': 'Casos Reales',
    'case-studies.subtitle': 'Análisis detallado de operaciones exitosas. Casos de estudio con métricas reales, ROI obtenido y lecciones aprendidas de inversionistas que confiaron en nuestra expertise.',
    'case-studies.back-home': 'Volver al inicio',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.contact': 'Contacto',
    'common.email': 'Email',
    'common.phone': 'Teléfono',
    'common.name': 'Nombre',
    'common.send': 'Enviar',
    'common.read-more': 'Leer más',
    'common.learn-more': 'Saber más',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.why-argentina': 'Why Argentina',
    'nav.services': 'Services',
    'nav.process': 'Process',
    'nav.case-studies': 'Case Studies',
    'nav.resources': 'Resources',
    'nav.pricing': 'Pricing',
    'nav.blog': 'Blog',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'header.schedule-consultation': 'Schedule consultation',
    
    // Hero Section
    'hero.title.part1': 'Your gateway to',
    'hero.title.part2': 'Buenos Aires',
    'hero.title.part3': 'real estate future',
    'hero.subtitle': 'We navigate the complexity of the Argentine market to transform doubts into exceptional rental opportunities. Comprehensive support from strategy to execution.',
    'hero.schedule-consultation': 'Schedule your consultation',
    'hero.watch-presentation': 'Watch presentation',
    'hero.free-consultation': 'Free initial consultation',
    'hero.total-transparency': 'Total transparency',
    'hero.secure-remote': 'Secure remote operation',
    'hero.play-teaser': 'Play teaser',
    'hero.teaser-description': 'Discover how we turn Argentine volatility into predictable profitability',
    'hero.average-roi': 'Average ROI',
    'hero.upside-potential': 'Upside potential',
    
    // Data Section
    'data.title': 'Numbers don\'t lie',
    'data.subtitle': 'Comparative data demonstrating the exceptional moment to invest in Buenos Aires',
    'data.international-comparison': 'International comparison (USD/m²)',
    
    // Philosophy Section
    'philosophy.badge': 'Antifragile Philosophy',
    'philosophy.title.part1': 'We thrive in',
    'philosophy.title.part2': 'uncertainty',
    'philosophy.subtitle': 'While others fear volatility, we leverage it. Buenos Aires offers unique opportunities for investors who understand how to navigate complexity.',
    'philosophy.exceptional-returns.title': 'Exceptional Returns',
    'philosophy.exceptional-returns.description': '8-15% annual ROI in USD. Prices 60% below historical peaks create unrepeatable opportunities.',
    'philosophy.exceptional-returns.stat': 'appreciation potential',
    'philosophy.legal-security.title': 'Legal Security',
    'philosophy.legal-security.description': 'Exhaustive due diligence, certified notary and power of attorney for 100% remote and secure operations.',
    'philosophy.legal-security.stat': 'successful operations',
    'philosophy.boutique-service.title': 'Boutique Service',
    'philosophy.boutique-service.description': 'From strategy to rental management. A specialized team dedicated exclusively to your success.',
    'philosophy.boutique-service.stat': 'comprehensive support',
    

    // Testimonials
    'testimonials.badge': 'Success Stories',
    'testimonials.title': 'Investors who trusted',
    'testimonials.subtitle': 'Professionals from around the world have chosen our expertise for their investments in Buenos Aires',
    'testimonials.see-more': 'See more success stories',
    'testimonials.quote1': '"14% ROI in the first year. The process was impeccably professional and completely transparent from the start."',
    'testimonials.quote2': '"100% remote operation from Madrid. Absolute legal security and support in every detail of the process."',
    'testimonials.quote3': '"Best investment decision in years. Combines exceptional profitability with truly boutique service."',

    // Blog Page
    'blog.title': 'Insights & Analysis',
    'blog.subtitle': 'Deep perspectives on real estate investments in Argentina',
    'blog.featured-articles': 'Featured articles',
    'blog.all-articles': 'All articles',
    'blog.newsletter.title': 'Stay informed',
    'blog.newsletter.subtitle': 'Receive exclusive analysis and investment opportunities directly in your email',
    'blog.newsletter.placeholder': 'Your email',
    'blog.newsletter.subscribe': 'Subscribe',
    'blog.newsletter.success': 'Subscription successful!',
    'blog.newsletter.success.description': 'You have successfully subscribed to our newsletter',
    'blog.newsletter.error': 'Error',
    'blog.newsletter.error.invalid': 'Please enter a valid email',
    'blog.newsletter.error.general': 'There was an error subscribing. Please try again.',
    'blog.read-more': 'Read more',
    'blog.back-to-blog': 'Back to blog',
    'blog.reading-time': 'read',

    // Why Argentina Page
    'why-argentina.title': 'Why Argentina now?',
    'why-argentina.subtitle': 'An investment thesis backed by hard data, economic cycles and a historic opportunity to buy world-class assets at emerging market prices.',
    'why-argentina.watch-analysis': 'Watch complete analysis',
    'why-argentina.download-pdf': 'Download free PDF',
    'why-argentina.macroeconomic-data': 'Macroeconomic data',
    'why-argentina.historical-cycles': 'Historical cycles',
    'why-argentina.expert-analysis': 'Expert analysis',
    'why-argentina.historic-opportunity': 'Historic opportunity',
    'why-argentina.play-analysis': 'Play analysis',
    'why-argentina.potential-multiplier': 'Potential multiplier',
    'why-argentina.video-version': 'Video version',
    'why-argentina.complete-analysis': 'Complete analysis (5-7 min)',
    'why-argentina.executive-pdf': 'Executive PDF',
    'why-argentina.free-download': 'Free download',
    'why-argentina.numbers-dont-lie': 'Numbers don\'t lie',
    'why-argentina.numbers-subtitle': 'Comparative data demonstrating the exceptional moment to invest in Buenos Aires',
    'why-argentina.international-comparison': 'International comparison (USD/m²)',
    'why-argentina.catalysts-title': 'Growth Catalysts',
    'why-argentina.catalysts-subtitle': 'Macro factors driving real estate appreciation in the medium term',
    'why-argentina.political-cycle': 'Political Cycle',
    'why-argentina.political-cycle.description': 'New pro-market government. Economic opening policies and exchange rate normalization.',
    'why-argentina.vaca-muerta': 'Vaca Muerta',
    'why-argentina.vaca-muerta.description': 'Second largest unconventional gas field in the world. Revenue potential of $200B+ over 20 years.',
    'why-argentina.exchange-rate': 'Exchange Rate',
    'why-argentina.exchange-rate.description': 'Imminent currency unification. Long-term equilibrium correction favors local assets.',
    'why-argentina.risks-title': 'Risks and how we mitigate them?',
    'why-argentina.risks-subtitle': 'Total transparency about challenges and our mitigation strategies',
    'why-argentina.risk1.title': 'Risk: Political/economic instability',
    'why-argentina.risk1.mitigation': 'Mitigation: Investment in physical assets (brick) denominated in USD. Diversification by neighborhoods and property types. Rental contracts in hard currency.',
    'why-argentina.risk2.title': 'Risk: Rental regulations',
    'why-argentina.risk2.mitigation': 'Mitigation: Robust legal structures. Constant regulatory monitoring. Flexibility between traditional rental and temporary (Airbnb) according to regulatory changes.',
    'why-argentina.risk3.title': 'Risk: Liquidity and exit',
    'why-argentina.risk3.mitigation': 'Mitigation: Selection of properties in prime areas with high demand. Network of local and international buyers. Exit strategy planned from day 1.',
    'why-argentina.schedule-consultation': 'Schedule a consultation',
    
    // Footer
    'footer.company': 'Company',
    'footer.company-description': 'We transform the uncertainty of the Argentine market into exceptional investment opportunities. Boutique expertise for sophisticated investors.',
    'footer.services': 'Services',
    'footer.service.strategic-consulting': 'Strategic Consulting',
    'footer.service.property-curation': 'Property Curation',
    'footer.service.financial-structuring': 'Financial Structuring',
    'footer.service.legal-due-diligence': 'Legal Due Diligence',
    'footer.service.asset-optimization': 'Asset Optimization',
    'footer.service.integral-management': 'Integral Management',
    'footer.resources': 'Resources',
    'footer.resource.investment-thesis': 'Investment Thesis',
    'footer.resource.research-analysis': 'Research & Analysis',
    'footer.resource.market-intelligence': 'Market Intelligence',
    'footer.resource.roi-calculator': 'ROI Calculator',
    'footer.resource.success-cases': 'Success Cases',
    'footer.resource.team': 'Team',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter-subtitle': 'Stay updated with exclusive insights',
    'footer.email-placeholder': 'Your email',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Services Page
    'services.title': '360° Services',
    'services.subtitle': 'Everything you need to successfully invest in Buenos Aires. From initial consultation to rental management, we handle every detail.',
    'services.main-title': 'Main Services',
    'services.main-subtitle': 'Each service is designed to eliminate friction and maximize your return on investment',
    'services.advisory.title': '1-on-1 Advisory',
    'services.advisory.price': '300 USD/hour',
    'services.advisory.description': 'Personalized consulting with local experts. Investment profile analysis and specific recommendations.',
    'services.advisory.feature1': 'Risk profile analysis',
    'services.advisory.feature2': 'Neighborhood recommendations',
    'services.advisory.feature3': 'Financing strategy',
    'services.advisory.feature4': 'Personalized ROI projection',
    'services.search.title': 'Area & Search',
    'services.search.price': 'Included in packages',
    'services.search.description': 'In-depth neighborhood research and active property search that meets your specific criteria.',
    'services.search.feature1': 'Detailed demographic analysis',
    'services.search.feature2': 'Urban growth projection',
    'services.search.feature3': 'Active property search',
    'services.search.feature4': 'Complete due diligence',
    'services.exchange.title': 'Currency Exchange',
    'services.exchange.price': 'Best market rate',
    'services.exchange.description': 'USDT/crypto to USD cash or ARS conversion at the best exchange rate. Secure and traceable process.',
    'services.exchange.feature1': 'USDT → USD cash',
    'services.exchange.feature2': 'Crypto → ARS',
    'services.exchange.feature3': 'Guaranteed competitive rate',
    'services.exchange.feature4': 'Secure and fast transfers',
    'services.legal.title': 'Legal Documentation',
    'services.legal.price': 'Comprehensive package',
    'services.legal.description': 'Complete CUIT/CDI management, tax documentation and legal structures for foreign investors.',
    'services.legal.feature1': 'CUIT/CDI processing',
    'services.legal.feature2': 'Bank account opening',
    'services.legal.feature3': 'Optimal tax structures',
    'services.legal.feature4': 'Apostilled documentation',
    'services.notary.title': 'Notary & Power of Attorney',
    'services.notary.price': 'Secure remote closing',
    'services.notary.description': 'Certified notary and power of attorney for remote purchase. 100% remote closing with legal guarantees.',
    'services.notary.feature1': 'Trusted notary',
    'services.notary.feature2': 'International power of attorney',
    'services.notary.feature3': 'Title verification',
    'services.notary.feature4': 'Certified remote closing',
    'services.renovation.title': 'Turnkey Renovation',
    'services.renovation.price': 'Comprehensive project',
    'services.renovation.description': 'Complete design, renovation and interior design. From purchase to rental without you having to travel.',
    'services.renovation.feature1': 'Architectural design',
    'services.renovation.feature2': 'Complete project management',
    'services.renovation.feature3': 'Professional interior design',
    'services.renovation.feature4': 'Turnkey delivery',
    'services.rental-title': 'Rental Management',
    'services.rental-subtitle': 'Two rental modalities to maximize your return according to your risk profile and objectives',
    'services.traditional.title': 'Traditional Rental',
    'services.traditional.description': 'Long-term residential rental management. Maximum stability and income predictability.',
    'services.traditional.feature1': '2-3 year contracts',
    'services.traditional.feature2': 'Verified tenants',
    'services.traditional.feature3': 'Solid guarantees',
    'services.traditional.feature4': 'Complete administration',
    'services.airbnb.title': 'Airbnb / Students',
    'services.airbnb.description': 'Temporary rental and international students. Higher rotation but superior yields.',
    'services.airbnb.feature1': 'Complete Airbnb management',
    'services.airbnb.feature2': 'Student rentals',
    'services.airbnb.feature3': '15-25% higher yields',
    'services.airbnb.feature4': 'Maintenance included',
    'services.rental-question': 'Not sure which modality suits you best?',
    'services.rental-button': 'Free personalized consultation',
    'services.rental-button-mobile': 'Personalized consultation',
    'services.guarantee-title': '100% Satisfaction Guarantee',
    'services.guarantee-subtitle': 'If you\'re not completely satisfied with our service in the first 30 days, we\'ll refund 100% of your investment. No questions asked.',
    'services.guarantee-stat1': '100%',
    'services.guarantee-label1': 'Successful operations',
    'services.guarantee-stat2': '24/7',
    'services.guarantee-label2': 'Available support',
    'services.guarantee-stat3': '30 days',
    'services.guarantee-label3': 'Money-back guarantee',


    // Process Page
    'process.title': 'Our Process',
    'process.subtitle': 'A proven process that takes you from initial idea to generating passive income in less than 3 months. Transparent, predictable and with step-by-step tracking.',
    'process.average-time-title': 'Average time',
    'process.average-time-value': '8-12 weeks',
    'process.average-time-desc': 'From initial consultation to first rental',
    'process.success-rate-title': 'Success rate',
    'process.success-rate-value': '100%',
    'process.success-rate-desc': 'Operations completed successfully',
    'process.satisfaction-title': 'Satisfaction',
    'process.satisfaction-value': '100%',
    'process.satisfaction-desc': 'Clients who recommend our service',
    'process.steps-title': '5 steps towards your successful investment',
    'process.steps-subtitle': 'Each step is designed to minimize risks and maximize transparency',
    'process.step1.title': 'Free Discovery Call',
    'process.step1.duration': '15 minutes',
    'process.step1.description': 'We learn about your objectives, budget and risk profile. We define initial strategy and realistic expectations.',
    'process.step1.detail1': 'Investment profile analysis',
    'process.step1.detail2': 'Available budget definition',
    'process.step1.detail3': 'Profitability and timeline objectives',
    'process.step1.detail4': 'Initial neighborhood recommendations',
    'process.step2.title': 'Mandate & Due Diligence',
    'process.step2.duration': '2-4 weeks',
    'process.step2.description': 'Active search and deep property analysis. Complete legal, technical and financial verification.',
    'process.step2.detail1': 'Active search based on criteria',
    'process.step2.detail2': 'Title and documentation verification',
    'process.step2.detail3': 'Detailed technical inspection',
    'process.step2.detail4': 'Projected profitability analysis',
    'process.step3.title': 'Offer & Notarial Closing',
    'process.step3.duration': '1-2 weeks',
    'process.step3.description': 'Negotiation, formal offer and remote notarial closing. Secure transfer with certified power of attorney.',
    'process.step3.detail1': 'Price and conditions negotiation',
    'process.step3.detail2': 'Legal documentation preparation',
    'process.step3.detail3': 'Notarial closing with remote power',
    'process.step3.detail4': 'Secure funds transfer',
    'process.step4.title': 'Construction Project',
    'process.step4.duration': '4-8 weeks',
    'process.step4.description': 'Turnkey design, renovation and interior design. Complete supervision until turnkey delivery.',
    'process.step4.detail1': 'Architectural and decorative design',
    'process.step4.detail2': 'Permits and contractors management',
    'process.step4.detail3': 'Daily construction supervision',
    'process.step4.detail4': 'Delivery with furniture included',
    'process.step5.title': 'Post-Purchase Administration',
    'process.step5.duration': 'Ongoing',
    'process.step5.description': 'Complete rental, maintenance and administration management. Monthly performance reports.',
    'process.step5.detail1': 'Tenant search and verification',
    'process.step5.detail2': 'Contract and collection management',
    'process.step5.detail3': 'Preventive and corrective maintenance',
    'process.step5.detail4': 'Monthly profitability reports',
    'process.includes': 'Includes:',
    'process.timeline-title': 'Typical project timeline',
    'process.timeline-subtitle': 'Weekly schedule from first contact to generating rent',
    'process.timeline.week1': 'Week 1',
    'process.timeline.milestone1': 'Discovery call + Search mandate',
    'process.timeline.week2': 'Week 2-3',
    'process.timeline.milestone2': 'Presentation of pre-selected options',
    'process.timeline.week3': 'Week 4',
    'process.timeline.milestone3': 'Due diligence + Formal offer',
    'process.timeline.week4': 'Week 5',
    'process.timeline.milestone4': 'Notarial closing + Transfer',
    'process.timeline.week5': 'Week 6-12',
    'process.timeline.milestone5': 'Construction project + Renovation',
    'process.timeline.week6': 'Week 13',
    'process.timeline.milestone6': 'Put to rent + First tenant',
    'process.final-title': 'Your property generating rent!',
    'process.final-description': 'At the end of the process you will have a quality asset generating passive income in USD.',
    'process.cta-title': 'Ready to get started?',
    'process.cta-subtitle': 'The first step is always a free 15-minute consultation. No commitment, just to get to know you and see if we are the right fit.',
    'process.cta-button': 'Schedule your free consultation',
    'process.cta-button-mobile': 'Schedule consultation',
    'process.cta-pricing': 'View rates and packages',
    'process.cta-benefit1': 'No initial commitment',
    'process.cta-benefit2': '100% free consultation',
    'process.cta-benefit3': 'Response within 24h',

    // Case Studies Page
    'case-studies.badge': 'Success Portfolio',
    'case-studies.title': 'Case Studies',
    'case-studies.subtitle': 'Detailed analysis of successful operations. Case studies with real metrics, ROI obtained and lessons learned from investors who trusted our expertise.',
    'case-studies.back-home': 'Back to home',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.contact': 'Contact',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.name': 'Name',
    'common.send': 'Send',
    'common.read-more': 'Read more',
    'common.learn-more': 'Learn more',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};