// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvhwdbslsapqqojuimoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2aHdkYnNsc2FwcXFvanVpbW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTUyNDksImV4cCI6MjA2Nzg3MTI0OX0.KDy-vbLS51COiKw5NnZje5f-1-bqFflbUc_2px_6CmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});